services:
  server:
    build: ./server
    ports:
      - "56789:56789"
    volumes:
      - ./server:/app
      - /app/dist
      - /app/node_modules
    networks:
      - cards_online_nw

  client:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - server
    networks:
      - cards_online_nw
  
networks:
  cards_online_nw:
    driver: bridge
